# Getting Started

```{r setup, include=FALSE, purl = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE,
                      fig.align = "center")

## Load packages 
library(tidyverse)
library(knitr)
library(coda)
```

## Welcome!

Welcome to the workshop on Bayesian inference with JAGS for ecologists. The field of Bayesian inference is very extensive with applications in all areas of research. There are many excellent book on Bayesian statistics, and my goal is not to try to reproduce all of the content they contain. Instead, I am hoping to provide you with a first look at the subject includes some hands on examples using both R the JAGS software package. 

The workshop is designed to allow you to work at you own pace. The material is divided into a number of sections organized using the tabs at the top of the page. Each tab (except this one) has several subtabs. Working through the tabs in order will lead you through a series of explanations, examples, and exercise that will introduce you to the basic concepts of Bayesian statistics and programming with JAGS. The content at the end of the course will also introduce you to some of the core ideas of Markov chain Monte Carlo (MCMC). By the end of the workshop you should be able to:

- Construct the Directed Acyclic Graph (DAG) for a simple statistical model.
- Understand the connection between a DAG and JAGS code for the same model.
- Run a model in JAGS using the functions from the `rjags` package in R.
- Summarize the results of a model based on the output from JAGS.
- Explain the basic workings of MCMC. 

Please don't hesitate to ask any questions.

Simon

## Setting Up

### Packages

You will need to have the `R` packages `coda`, `rjags`, and `ggmcmc` installed to run the code in this workshop. You can install these with the function `install.packages()` in the `R` console or using the `install` button from the `Packages` pane in `RStudio`. I suggest that you install these now so that you don't get hung up on this later. Let me know if you need any help with this.

### Working directory

You will also need to set your working directory in `R` to the location of *this file* to access the files for the examples. You can set the working directory using the menu command `Session > Set Working Directory > Choose Directory...` in `RStudio`. Alternatively, you can use the command `setwd()` in the `R` console. 


